vbar_categorical:
  y_range: [0, 100000]
  n_points_range: [2, 15]
  x_distn: ["linear"]
  # shape: ["random", "random", "random", "random", "linear_inc", "linear_dec", "cluster"]
  shape: ["random", "random", "random", "random"]
  color_sources: ["resources/random_text_color_2.txt"]

hbar_categorical:
  y_range: [0, 100000]
  n_points_range: [2, 15]
  x_distn: ["linear"]
  # shape: ["random", "random", "random", "random", "linear_inc", "linear_dec", "cluster"]
  shape: ["random", "random", "random", "random"]
  color_sources: ["resources/random_text_color.txt"]

line:
  x_range: [0, 9000]
  y_range: [0, 100000]
  n_points_range: [5, 50]
  x_distn: ["linear"]
  # shape: ["linear", "linear_with_noise", "quadratic"]
  shape: ["random", "random", "random", "random"]
  n_classes_range: [1, 1]
  color_sources: ["resources/random_text_color.txt"]
  solid_pr: 0.5

dot_line:
  x_range: [0, 9000]
  y_range: [0, 100000]
  n_points_range: [5, 50]
  x_distn: ["linear"]
  # shape: ["linear", "linear_with_noise", "quadratic"]
  shape: ["random", "random", "random", "random"]
  n_classes_range: [1, 1]
  color_sources: ["resources/random_text_color.txt"]

pie:
  color_sources: ["resources/random_text_color.txt"]
  n_classes_range: [2, 7]
